# Netlify configuration for GlamAI frontend

[build]
  # Directory to change to before starting a build
  base = "frontend/"

  # Build command
  command = "npm run build"

  # Directory to publish (relative to base directory)
  publish = "dist/"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API proxy for development (optional)
# Uncomment if you want to proxy API calls through Netlify
# [[redirects]]
#   from = "/api/*"
#   to = "https://glamai-backend.onrender.com/:splat"
#   status = 200
#   force = true