services:
  - type: web
    name: glamai-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CLAUDE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PRODUCTION_FRONTEND_URL
        sync: false